# created by Mike Czarny
version: '3'

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.60.0.0/24

services:
  server01:
    container_name: server01
    image: ${SERVER_IMAGE}
    stdin_open: true
    tty: true
    networks:
      app_network:
        ipv4_address: ${SERVER1_IP}

  server02:
    container_name: server02
    image: ${SERVER_IMAGE}
    stdin_open: true
    tty: true
    networks:
      app_network:
        ipv4_address: ${SERVER2_IP}
  
  server03:
    image: ${SERVER_IMAGE}
    container_name: server03
    stdin_open: true
    tty: true
    networks:
      app_network:
        ipv4_address: ${SERVER3_IP}
  
  load_balancer:
    container_name: haproxy
    depends_on:
      - server01
      - server02
      - server03
    image: ${HAPROXY_IMAGE} 
    networks:
      app_network:
        ipv4_address: ${HAPROXY_IP}
    ports:
      - "127.0.0.1:4141:${HAPROXY_PORT}"
      - "127.0.0.1:9000:9000"
