# created by Mike Czarny
version: '3'

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.60.0.0/24

services:
  server01:
    container_name: server01
    image: ${SERVER_IMAGE}
    stdin_open: true
    tty: true
    networks:
      app_network:
        ipv4_address: ${SERVER1_IP}

  server02:
    container_name: server02
    image: ${SERVER_IMAGE}
    stdin_open: true
    tty: true
    networks:
      app_network:
        ipv4_address: ${SERVER2_IP}
  
  server03:
    image: ${SERVER_IMAGE}
    container_name: server03
    stdin_open: true
    tty: true
    networks:
      app_network:
        ipv4_address: ${SERVER3_IP}
  
  load_balancer:
    container_name: haproxy
    depends_on:
      - server01
      - server02
      - server03
    image: ${HAPROXY_IMAGE} 
    networks:
      app_network:
        ipv4_address: ${HAPROXY_IP}
    ports:
      - "127.0.0.1:4141:${HAPROXY_PORT}"
      - "127.0.0.1:9000:9000" 

  etcd01:
    image: quay.io/coreos/etcd:v3.3.10
    container_name: etcd01
#    ports:
#        - 2379:2379
#        - 2380:2380
#        - 4001:4001
    command: >
        etcd -name etcd01
        -advertise-client-urls http://${ETCD1_IP}:2379,http://${ETCD1_IP}:4001
        -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
        -initial-advertise-peer-urls http://${ETCD1_IP}:2380
        -listen-peer-urls http://0.0.0.0:2380
        -initial-cluster-token etcd-cluster-1
        -initial-cluster etcd01=http://${ETCD1_IP}:2380,etcd02=http://${ETCD2_IP}:2380,etcd03=http://${ETCD3_IP}:2380
        -initial-cluster-state new
    networks:
      app_network:
        ipv4_address: ${ETCD1_IP}
  etcd02:
    image: quay.io/coreos/etcd:v3.3.10
    container_name: etcd02
#    ports:
#        - 2379:2379
#        - 2380:2380
#        - 4001:4001
    command: >
        etcd -name etcd02
        -advertise-client-urls http://${ETCD2_IP}:2379,http://${ETCD2_IP}:4001
        -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
        -initial-advertise-peer-urls http://${ETCD2_IP}:2380
        -listen-peer-urls http://0.0.0.0:2380
        -initial-cluster-token etcd-cluster-1
        -initial-cluster etcd01=http://${ETCD1_IP}:2380,etcd02=http://${ETCD2_IP}:2380,etcd03=http://${ETCD3_IP}:2380
        -initial-cluster-state new
    networks:
      app_network:
        ipv4_address: ${ETCD2_IP}
  etcd03:
    image: quay.io/coreos/etcd:v3.3.10
    container_name: etcd03
    ## since i am testing this cluster via localhost interface in ipython
    ## i am just exposing one of the nodes ports
    ports:
        - 2379:2379
        - 2380:2380
        - 4001:4001
    command: >
        etcd -name etcd03
        -advertise-client-urls http://${ETCD3_IP}:2379,http://${ETCD3_IP}:4001
        -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
        -initial-advertise-peer-urls http://${ETCD3_IP}:2380
        -listen-peer-urls http://0.0.0.0:2380
        -initial-cluster-token etcd-cluster-1
        -initial-cluster etcd01=http://${ETCD1_IP}:2380,etcd02=http://${ETCD2_IP}:2380,etcd03=http://${ETCD3_IP}:2380
        -initial-cluster-state new
    networks:
      app_network:
        ipv4_address: ${ETCD3_IP}
