# created by Mike Czarny
version: '3'

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.60.0.0/24

services:
  server1:
    image: ${SERVER_IMAGE}
    networks:
      app_network:
        ipv4_address: ${SERVER1_IP}
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:5151:${SERVER_PORT}"
    command:
      - "-p 6000"
      #- "-H 172.60.0.10"

  server2:
    image: ${SERVER_IMAGE}
    networks:
      app_network:
        ipv4_address: ${SERVER2_IP}
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:5152:${SERVER_PORT}"
    command:
      - "-p 6000"
     # - "-H 0.0.0.0"
  
  server3:
    image: ${SERVER_IMAGE}
    networks:
      app_network:
        ipv4_address: ${SERVER3_IP}
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:5153:${SERVER_PORT}"
    command:
      - "-p 6000"
     # - "-H 0.0.0.0"
  
  load_balancer:
    container_name: haproxy
    depends_on:
      - server1
      - server2
      - server3
    image: haproxy:1.8 
    environment:
     # - BALANCE=leastconn
      - BALANCE=roundrobin
    networks:
      app_network:
        # static IP for proxy
        ipv4_address: 172.60.0.2
